apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: payment
    version: v1
  name: payment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      containers:
      - env:
        image: siddharth67/istio-payment:v1
        imagePullPolicy: IfNotPresent
        name: payment
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
